### ISSUE TITLE
Unverify users

### ISSUE THREAD

**Issue by Luke100000** [Pequla/ForgeLink#1]
SuperLink related tho I did not find the repo.

I would like to see a way to unverify someone using commands, e.g.: this user here https://data.pequla.com/data-discord.html?id=126835218106548225 has no longer access to his Discord Account. I can neither ban him (account not on the server, thus discord command rejected) nor remove him manually as there is no `/unverify user`.

Did I overlooked something?

**Comment by Pequla** [comment]
Yeah superlink is private, i am just too lazy to remove the hardcoded bot token (... yeah)

I have manually unlined that person, for now all the issues like this have to be done my me manually, at some point i will def make this available for server admins

Thank you for using the app
